spring:
  profiles.active: develop
  datasource:
    url: jdbc:mysql://localhost/develop
    username: testuser
    password: testuser
    driverClassName: com.mysql.jdbc.Driver
    maximum-pool-size: 10
