package com.shinya.sample.spring4.web.model;

import java.util.Date;

public class Messages {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.id
     *
     * @mbggenerated Sun Oct 25 22:56:19 JST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.user_id
     *
     * @mbggenerated Sun Oct 25 22:56:19 JST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.title
     *
     * @mbggenerated Sun Oct 25 22:56:19 JST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.update_date
     *
     * @mbggenerated Sun Oct 25 22:56:19 JST 2015
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.create_date
     *
     * @mbggenerated Sun Oct 25 22:56:19 JST 2015
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.message
     *
     * @mbggenerated Sun Oct 25 22:56:19 JST 2015
     */
    private String message;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.id
     *
     * @return the value of messages.id
     *
     * @mbggenerated Sun Oct 25 22:56:19 JST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.id
     *
     * @param id the value for messages.id
     *
     * @mbggenerated Sun Oct 25 22:56:19 JST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.user_id
     *
     * @return the value of messages.user_id
     *
     * @mbggenerated Sun Oct 25 22:56:19 JST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.user_id
     *
     * @param userId the value for messages.user_id
     *
     * @mbggenerated Sun Oct 25 22:56:19 JST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.title
     *
     * @return the value of messages.title
     *
     * @mbggenerated Sun Oct 25 22:56:19 JST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.title
     *
     * @param title the value for messages.title
     *
     * @mbggenerated Sun Oct 25 22:56:19 JST 2015
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.update_date
     *
     * @return the value of messages.update_date
     *
     * @mbggenerated Sun Oct 25 22:56:19 JST 2015
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.update_date
     *
     * @param updateDate the value for messages.update_date
     *
     * @mbggenerated Sun Oct 25 22:56:19 JST 2015
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.create_date
     *
     * @return the value of messages.create_date
     *
     * @mbggenerated Sun Oct 25 22:56:19 JST 2015
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.create_date
     *
     * @param createDate the value for messages.create_date
     *
     * @mbggenerated Sun Oct 25 22:56:19 JST 2015
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.message
     *
     * @return the value of messages.message
     *
     * @mbggenerated Sun Oct 25 22:56:19 JST 2015
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.message
     *
     * @param message the value for messages.message
     *
     * @mbggenerated Sun Oct 25 22:56:19 JST 2015
     */
    public void setMessage(String message) {
        this.message = message;
    }
}